"""MobPlan_Table

Revision ID: 08c48b6e3b33
Revises: 92f0207108d3
Create Date: 2020-05-02 23:07:24.373620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c48b6e3b33'
down_revision = '92f0207108d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mob_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('Price', sa.Integer(), nullable=True),
    sa.Column('Data', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mob_plan')
    # ### end Alembic commands ###
