"""SupportTel_Table

Revision ID: 2e0b6b80ae25
Revises: 08c48b6e3b33
Create Date: 2020-05-03 13:38:14.504648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0b6b80ae25'
down_revision = '08c48b6e3b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tel',
    sa.Column('Telno', sa.Integer(), nullable=False),
    sa.Column('Service', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Telno')
    )
    op.drop_constraint(None, 'pay', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pay', 'user', ['id'], ['id'])
    op.drop_table('support_tel')
    # ### end Alembic commands ###
