"""MyTVSuper_Table

Revision ID: 4831e933d59a
Revises: db06b7e65d1e
Create Date: 2020-05-03 19:15:32.725630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4831e933d59a'
down_revision = 'db06b7e65d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_tv_super',
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('PlanLevel', sa.VARCHAR(length=20), nullable=True),
    sa.Column('channel', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('PlanID')
    )
    op.drop_constraint(None, 'pay', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pay', 'user', ['id'], ['id'])
    op.drop_table('my_tv_super')
    # ### end Alembic commands ###
