"""permission_Table

Revision ID: c61af01a221f
Revises: 4831e933d59a
Create Date: 2020-05-03 19:41:04.862553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61af01a221f'
down_revision = '4831e933d59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userName', sa.VARCHAR(length=50), nullable=True),
    sa.Column('permissionLevel', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.drop_constraint(None, 'pay', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pay', 'user', ['id'], ['id'])
    op.drop_table('permission')
    # ### end Alembic commands ###
