"""ReferralRewards_Table

Revision ID: db06b7e65d1e
Revises: eae3c1015e35
Create Date: 2020-05-03 17:00:00.746841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db06b7e65d1e'
down_revision = 'eae3c1015e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DesignatedService', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Referrers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'pay', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pay', 'user', ['id'], ['id'])
    op.drop_table('referral_rewards')
    # ### end Alembic commands ###
