"""GlobalTalk_Table

Revision ID: eae3c1015e35
Revises: 2e0b6b80ae25
Create Date: 2020-05-03 14:16:54.222240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae3c1015e35'
down_revision = '2e0b6b80ae25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_talk',
    sa.Column('Function', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Function')
    )
    op.drop_constraint(None, 'pay', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pay', 'user', ['id'], ['id'])
    op.drop_table('global_talk')
    # ### end Alembic commands ###
